/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class printf2_Printf2 */

#ifndef _Included_printf2_Printf2
#define _Included_printf2_Printf2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     printf2_Printf2
 * Method:    sprint
 * Signature: (Ljava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_printf2_Printf2_sprint
  (JNIEnv *, jclass, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
