/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class employee_Employee */

#ifndef _Included_employee_Employee
#define _Included_employee_Employee
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     employee_Employee
 * Method:    raiseSalary
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_employee_Employee_raiseSalary
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
